<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_acceptCookies</name>
   <tag></tag>
   <elementGuidId>2f47d149-455a-4426-a1ee-908a93830cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hs-eu-confirmation-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
